# Generated by Django 5.1.6 on 2025-02-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signInSignUp', '0002_alter_users_email_alter_users_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_actice',
            new_name='is_active',
        ),
    ]
