# Generated by Django 5.1.6 on 2025-03-04 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signInSignUp', '0005_doctor_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user_id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signInSignUp.users'),
        ),
    ]
